//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        public int id { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string FirstName { get; set; }
        public string PatientFileNumber { get; set; }
        public System.DateTime EnrolledDate { get; set; }
        public string MaritalStatus { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int Age { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string NationalIDNo { get; set; }
        public string CellPhoneNumber { get; set; }
        public string HomePhoneNumber { get; set; }
        public string Occupation { get; set; }
        public string Employer { get; set; }
        public string EmployerPhoneNumber { get; set; }
        public string ReasonForVisit { get; set; }
    }
}
